# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  stock:
    build:
      context: "/Users/AndreTrindade/Documents/Old_lapTop/Programacao/WorkSpace/my-wallet"
      dockerfile: "Services/StockService/StockService.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/StockService.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "stock:dev"
    ports: []
    volumes:
    - "/Users/AndreTrindade/.nuget/packages:/root/.nuget/packages"
    - "/Users/AndreTrindade/Documents/Old_lapTop/Programacao/WorkSpace/my-wallet/Services/StockService/StockService.Api:/app:rw"
    - "/Users/AndreTrindade/Documents/Old_lapTop/Programacao/WorkSpace/my-wallet:/src:rw"
    working_dir: "/app"
  wallet:
    build:
      context: "/Users/AndreTrindade/Documents/Old_lapTop/Programacao/WorkSpace/my-wallet"
      dockerfile: "Services/WalletService/WalletService.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WalletService.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "wallet:dev"
    ports: []
    volumes:
    - "/Users/AndreTrindade/.nuget/packages:/root/.nuget/packages"
    - "/Users/AndreTrindade/Documents/Old_lapTop/Programacao/WorkSpace/my-wallet/Services/WalletService/WalletService.Api:/app:rw"
    - "/Users/AndreTrindade/Documents/Old_lapTop/Programacao/WorkSpace/my-wallet:/src:rw"
    working_dir: "/app"
